export const articles = [
    {
        "id": "1",
        "name": "ENSALADA CHINA",
        "category": "ENTRANTES",
        "pvp": 3.35,
    },
    {
        "id": "2",
        "name": "ENSALADA BROTES DE SOJA",
        "category": "ENTRANTES",
        "pvp": 3.50,
    },
    {
        "id": "3",
        "name": "ROLLITO DE PRIMAVERA",
        "category": "ENTRANTES",
        "pvp": 1.70,
    },
    {
        "id": "4A",
        "name": "ROLLITOS DE VERDURA 8U.",
        "category": "ENTRANTES",
        "pvp": 3.00,
    },
    {
        "id": "5",
        "name": "SOPA DE LA CASA",
        "category": "ENTRANTES",
        "pvp": 3.20,
    },
    {
        "id": "7",
        "name": "SOPA DE FIDEOS CHINOS CON POLLO",
        "category": "ENTRANTES",
        "pvp": 3.00,
    },
    {
        "id": "8",
        "name": "SOPA DE MAIZ Y HUEVO",
        "category": "ENTRANTES",
        "pvp": 2.95,
    },
    {
        "id": "12",
        "name": "SOPA PICANTE",
        "category": "ENTRANTES",
        "pvp": 2.95,
    },
    {
        "id": "14",
        "name": "WAN TAN FRITOS",
        "category": "ENTRANTES",
        "pvp": 3.5,
    },
    {
        "id": "83",
        "name": "PAN CHINO",
        "category": "ENTRANTES",
        "pvp": 1.50,
    },
    {
        "id": "104",
        "name": "PATATAS FRITAS",
        "category": "ENTRANTES",
        "pvp": 3.25,
    },
    {
        "id": "105",
        "name": "PAN DE GAMBA",
        "category": "ENTRANTES",
        "pvp": 1,
    },
    {
        "id": "15",
        "name": "ARROZ FRITO TRES DELICIAS",
        "category": "ARROCES",
        "pvp": 4.4,
    },
    {
        "id": "15A",
        "name": "ARROZ FRITO TRES DELICIAS CON CURRY",
        "category": "ARROCES",
        "pvp": 6.3,
    },
    {
        "id": 16,
        "name": "ARROZ FRITO CON GAMBAS",
        "category": "ARROCES",
        "pvp": 4.9,
    },
    {
        "id": "17",
        "name": "ARROZ FRITO CON VERDURAS",
        "category": "ARROCES",
        "pvp": 4.4,
    },
    {
        "id": "18",
        "name": "ARROZ ORIENTAL",
        "category": "ARROCES",
        "pvp": 4.55,
    },
    {
        "id": "19",
        "name": "ARROZ CON GAMBAS EN SALSA CURRY",
        "category": "ARROCES",
        "pvp": 4.8,
    },
    {
        "id": "20",
        "name": "ARROZ CON POLLO EN SALSA CURRY",
        "category": "ARROCES",
        "pvp": 4.8,
    },
    {
        "id": "21",
        "name": "ARROZ BLANCO",
        "category": "ARROCES",
        "pvp": 1.8,
    },
    {
        "id": "60",
        "name": "ARROZ DE LA CASA",
        "category": "ARROCES",
        "pvp": 5.15,
    },
    {
        "id": "60A",
        "name": "ARROZ CON TERNERA",
        "category": "ARROCES",
        "pvp": 6.45,
    },
    {
        "id": "60B",
        "name": "ARROZ DE LA CASA CURRY",
        "category": "ARROCES",
        "pvp": 6.35,
    },
    {
        "id": "22",
        "name": "TALLARINES FRITOS CON GAMBAS",
        "category": "TALLARINES Y FIDEOS",
        "pvp": 4.9,
    },
    {
        "id": "23",
        "name": "TALLARINES FRITOS CON POLLO",
        "category": "TALLARINES Y FIDEOS",
        "pvp": 4.9,
    },
    {
        "id": "24",
        "name": "TALLARINES FRITOS CON TERNERA",
        "category": "TALLARINES Y FIDEOS",
        "pvp": 4.95,
    },
    {
        "id": "87",
        "name": "FIDEOS CHINOS CON GAMBAS",
        "category": "TALLARINES Y FIDEOS",
        "pvp": 5.4,
    },
    {
        "id": "88",
        "name": "FIDEOS CHINOS CON TERNERA",
        "category": "TALLARINES Y FIDEOS",
        "pvp": 5.45,
    },
    {
        "id": "89",
        "name": "FIDEOS CHINOS CON POLLO",
        "category": "TALLARINES Y FIDEOS",
        "pvp": 5.4,
    },
    {
        "id": "26",
        "name": "BAMB Y SETAS CHINAS SALTEADAS",
        "category": "VERDURAS Y TORTILLAS",
        "pvp": 4.7,
    },
    {
        "id": "27",
        "name": "BROTES DE SOJA FRITAS",
        "category": "VERDURAS Y TORTILLAS",
        "pvp": "3,90 ",
    },
    {
        "id": "28",
        "name": "MEZCLA DE VERDURAS SALTEADAS",
        "category": "VERDURAS Y TORTILLAS",
        "pvp": 4.1,
    },
    {
        "id": "30",
        "name": "TORTILLA CON SALSA \"FU YUN\"",
        "category": "VERDURAS Y TORTILLAS",
        "pvp": 3.6,
    },
    {
        "id": "31",
        "name": "TORTILLA DE GAMBAS",
        "category": "VERDURAS Y TORTILLAS",
        "pvp": 4.1,
    },
    {
        "id": "32",
        "name": "TORTILLA DE POLLO",
        "category": "VERDURAS Y TORTILLAS",
        "pvp": 3.6,
    },
    {
        "id": "33",
        "name": "TORTILLA DE JAMON",
        "category": "VERDURAS Y TORTILLAS",
        "pvp": 3.6,
    },
    {
        "id": "34",
        "name": "BOLAS DE POLLO FRITAS",
        "category": "POLLO",
        "pvp": 5.6,
    },
    {
        "id": "34J",
        "name": "BOLAS DE POLLO SIN HUESO",
        "category": "POLLO",
        "pvp": 6.5,
    },
    {
        "id": "35",
        "name": "POLLO CON BAMBú Y SETAS CHINA",
        "category": "POLLO",
        "pvp": 6.25,
    },
    {
        "id": "35A",
        "name": "POLLO CON CHAMPIONES",
        "category": "POLLO",
        "pvp": 6.5,
    },
    {
        "id": "36",
        "name": "POLLO CON SALSA AGRidULCE",
        "category": "POLLO",
        "pvp": 5.6,
    },
    {
        "id": "37",
        "name": "POLLO CON SALSA PICANTE",
        "category": "POLLO",
        "pvp": 5.55,
    },
    {
        "id": "38",
        "name": "POLLO CON ALMENDRAS",
        "category": "POLLO",
        "pvp": 5.55,
    },
    {
        "id": "39",
        "name": "POLLO CON NUECES",
        "category": "POLLO",
        "pvp": 5.55,
    },
    {
        "id": "40",
        "name": "POLLO AL CURRY",
        "category": "POLLO",
        "pvp": 5.55,
    },
    {
        "id": "41",
        "name": "POLLO CON PIA",
        "category": "POLLO",
        "pvp": 5.6,
    },
    {
        "id": "42",
        "name": "POLLO AL LIMON",
        "category": "POLLO",
        "pvp": 6,
    },
    {
        "id": "43",
        "name": "POLLO CON BROTES DE SOJA",
        "category": "POLLO",
        "pvp": 5.55,
    },
    {
        "id": "44",
        "name": "CHOP-SUEY DE POLLO",
        "category": "POLLO",
        "pvp": 5.55,
    },
    {
        "id": "45",
        "name": "TERNERA CON BAMB Y SETAS CHINAS",
        "category": "TERNERA",
        "pvp": 7.35,
    },
    {
        "id": "46",
        "name": "TERNERA CON SALSA DE OSTRAS",
        "category": "TERNERA",
        "pvp": 7,
    },
    {
        "id": "47",
        "name": "TERNERA CON SALSA PICANTE",
        "category": "TERNERA",
        "pvp": 6.95,
    },
    {
        "id": "48",
        "name": "TERNERA CON CHAMPIONES",
        "category": "TERNERA",
        "pvp": 6.95,
    },
    {
        "id": "50",
        "name": "TERNERA AL CURRY",
        "category": "TERNERA",
        "pvp": 6.95,
    },
    {
        "id": "51",
        "name": "TERNERA CON CEBOLLA",
        "category": "TERNERA",
        "pvp": 6.95,
    },
    {
        "id": "52",
        "name": "TERNERA CON PIMIENTOS VERDES",
        "category": "TERNERA",
        "pvp": 6.95,
    },
    {
        "id": "53",
        "name": "TERNERA CON BROTES DE SOJA",
        "category": "TERNERA",
        "pvp": 6.95,
    },
    {
        "id": "54",
        "name": "CHOP-SUEY DE TERNERA",
        "category": "TERNERA",
        "pvp": 6.95,
    },
    {
        "id": "56",
        "name": "CERDO CON SALSA AGRidULCE",
        "category": "CERDO",
        "pvp": 6.35,
    },
    {
        "id": "62",
        "name": "COSTILLAS DE CERDO ASADAS",
        "category": "CERDO",
        "pvp": 6.7,
    },
    {
        "id": "82",
        "name": "COSTILLAS DE CERDO CON SALSA AGRidULCE",
        "category": "CERDO",
        "pvp": 6.9,
    },
    {
        "id": "64",
        "name": "GAMBAS AL ESTILO CHINO",
        "category": "MARISCOS",
        "pvp": 6.45,
    },
    {
        "id": "65",
        "name": "GAMBAS CON BAMBÚ Y SETAS CHINAS",
        "category": "MARISCOS",
        "pvp": 6.70,
    },
    {
        "id": "66",
        "name": "GAMBAS AL CURRY",
        "category": "MARISCOS",
        "pvp": 6.45,
    },
    {
        "id": "66A",
        "name": "GAMBAS CON SALSA PICANTE",
        "category": "MARISCOS",
        "pvp": 6.45,
    },
    {
        "id": "68",
        "name": "CHOP-SUEY DE GAMBAS",
        "category": "MARISCOS",
        "pvp": 6.45,
    },
    {
        "id": "70",
        "name": "LANGOSTINOS FRITOS",
        "category": "MARISCOS",
        "pvp": 6.8,
    },
    {
        "id": "71",
        "name": "BUUELOS DE GAMBAS",
        "category": "MARISCOS",
        "pvp": 6.8,
    },
    {
        "id": "29",
        "name": "FAMILIA FELIZ",
        "category": "PLATOS ESPECIALES",
        "pvp": 5.95,
    },
    {
        "id": "85",
        "name": "GAMBAS AL \"CHINA TOWN\"",
        "category": "PLATOS ESPECIALES",
        "pvp": 7.15,
    },
    {
        "id": "90",
        "name": "KU-BAR TRES DELICIAS",
        "category": "PLATOS ESPECIALES",
        "pvp": 6.45,
    },
    {
        "id": "92",
        "name": "KU-BAR CON GAMBAS",
        "category": "PLATOS ESPECIALES",
        "pvp": 6.95,
    },
    {
        "id": "94",
        "name": "TERNERA AL \"CHINA TOWN\"",
        "category": "PLATOS ESPECIALES",
        "pvp": 7.55,
    },
    {
        "id": "95",
        "name": "POLLO AL \"CHINA TOWN\"",
        "category": "PLATOS ESPECIALES",
        "pvp": 6.45,
    },
    {
        "id": "97",
        "name": "POLLO CON PATATAS",
        "category": "PLATOS ESPECIALES",
        "pvp": 5.5,
    },
    {
        "id": "100",
        "name": "TERNERA CON PATATAS",
        "category": "PLATOS ESPECIALES",
        "pvp": 6.15,
    },
    {
        "id": "108",
        "name": "CANGREJO AL \"CHINA TOWN\"",
        "category": "PLATOS ESPECIALES",
        "pvp": 10.95,
    },
    {
        "id": "77",
        "name": "PATO FRITO CON BAMB Y SETAS",
        "category": "PATO",
        "pvp": 9.1,
    },
    {
        "id": "78",
        "name": "PATO FRITO ORIENTAL",
        "category": "PATO",
        "pvp": 9.1,
    },
    {
        "id": "79",
        "name": "PATO FRITO CON PIA",
        "category": "PATO",
        "pvp": 9.1,
    },
    {
        "id": "01",
        "name": "GASTO ENVIO",
        "category": "OTROS",
        "pvp": 1,
    },
    {
        "id": "2M",
        "name": "MENU PARA 2",
        "category": "MENU",
        "pvp": 22,
    },
    {
        "id": "3M",
        "name": "MENU PARA 3",
        "category": "MENU",
        "pvp": 33.00,
    },
    {
        "id": "4M",
        "name": "MENU PARA 4",
        "category": "MENU",
        "pvp": 44.00,
    },
    {
        "id": "5M",
        "name": "MENU PARA 5",
        "category": "MENU",
        "pvp": 55.00,
    },
    {
        "id": "6M",
        "name": "MENU PARA 6",
        "category": "MENU",
        "pvp": 66.00,
    }
]